#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:sample;DB_CLOSE_DELAY=-1
#    username: sa
#    password:

